### ISSUE TITLE
PDF download 

### ISSUE THREAD

**Issue by brchla** [PankratzLab/DonorCheck#11]
SureTyper PDF file will not import. Error message appears (see below)

Error message: Could not read donor data from PDF. Please notify the developers as this may indicate the data has changed.

**Comment by hinerm** [comment]
@brchla can you share the PDF with the [DonorCheck mailing list](https://groups.google.com/a/umn.edu/forum/#!forum/donor_check)?

SureTyper PDFs do not seem to have have a guaranteed, consistent structure... so we're finding that some contain different sections, or are ordered differently.

Unfortunately we need an example of the PDF to figure out what's different.

Thank you for your report!

**Comment by brchla** [comment]
Can I email you a copy of our PDF file?

[Description: Description: Description: Description: cid:image011.png@01D0CF66.DB19CF60]

Bobbie Rhodes-Clark, PhD.
Director-In-Training, Dialysis Clinic, Inc.
1616 Hayes Street, Nashville, TN, 37203
t: 615-321-0212 | f: 615-321-4880 | w: www.dciinc.org<http://www.dciinc.org/>
[Description: Description: extra small social icons-01]<https://www.facebook.com/DialysisClinicInc/?ref=hl>[Description: Description: extra small social icons-02]<https://twitter.com/DCI_Dialysis>[Description: Description: extra small social icons-03]<https://www.instagram.com/dci_dialysis/>[Description: Description: extra small social icons-04]<https://www.linkedin.com/company/dialysis-clinic-inc->[Description: Description: extra small social icons-05]<https://www.youtube.com/c/DialysisClinicInc1971>
“We are a non-profit service organization. The care of the patient is our reason for existence.”
Learn more about DCI Career Opportunities at www.dciinc.jobs<http://www.dciinc.jobs/>. We have special incentives in certain markets. Ask me about the employee referral program.

**Comment by hinerm** [comment]
@brchla absolutely: [hine0116@umn.edu](mailto:hine0116@umn.edu)

**Comment by hinerm** [comment]
Fixed in 039fe0d061bed111fa393012f2b08cf794e60f5f
