### ISSUE TITLE
'Next' button inactive after uploading donor files 

### ISSUE THREAD

**Issue by dfallon1** [PankratzLab/DonorCheck#47]
I just updated to DonorCheck version 15 his morning and I am able to input donor files successfully (PDF and HTML). However, the 'Next' button is always grayed out/inactive and I am unable to select it. I was using version 14 successfully this weekend. I updated my Java to the below version this morning as well to Java version 8 Update 421.

**Comment by rcoleb** [comment]
Fixed in v1.2.2
